spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/auth
    username: root
    password: root
mybatis:
  configuration:
    map-underscore-to-camel-case: true